export const Checkout = {
    "items": [],
    "onNextStep": () => { },
    "onDeleteCart": () => { },
    "onIncreaseQuantity": () => { },
    "onDecreaseQuantity": () => { },
    "onApplyDiscount": () => { },
    "onApplyShipping": () => { },
    "onCreateBilling": () => { },
    "onReset": () => { },
    "subtotal": 0,
    "total": 0,
    "discount": 0,
    "shipping": 0,
    "totalItems": 0,
    "canReset": true,
    "completed": false,
    "activeStep": 0,
    "billing": null,
}