export const mfConfig = {
  name: "components",
  exposes: {
    "./NewestBooking": "./src/post/newest-booking.tsx",
    "./Upload": "./src/upload/upload.tsx",
    "./Table": "./src/table/table.tsx",
    "./ProductCard": "./src/modules/shop/products/ProductCard.tsx",
    "./ProductsView": "./src/modules/shop/products/ProductsView.tsx",
    "./ProductView": "./src/modules/shop/product/ProductView.tsx",
    "./CheckoutView": "./src/modules/shop/checkout/CheckoutView.tsx",
    "./DashboardLayoutView": "./src/modules/dashboard/dashboardLayoutView/DashboardLayoutView.tsx",
    "./ShopDashboardListView": "./src/modules/shop-dashboard/shop-dashboard-list/shop-dashboard-list-view.tsx",
    "./ShopDashboardDetailsView": "./src/modules/shop-dashboard/shop-dashboard-details/shop-dashboard-details-view.tsx",
    "./ShopDashboardCreateView": "./src/modules/shop-dashboard/shop-dashboard-create/shop-dashboard-create-view.tsx",
    "./ShopDashboardEditView": "./src/modules/shop-dashboard/shop-dashboard-edit/shop-dashboard-edit-view.tsx",
    "./OrderDashboardListView": "./src/modules/order-dashboard/order-dashboard-list/order-dashboard-list-view.tsx",
    "./OrderDashboardDetailsView": "./src/modules/order-dashboard/order-dashboard-details/order-dashboard-details-view.tsx",
    "./CalendarDashboardView": "./src/modules/calendar-dashboard/calendar-dashboard-view.tsx",
  },
  shared: ["react", "react-dom"],
};
